/*  LAYOUT */
export const TOGGLE_LAYOUT = 'TOGGLE_LAYOUT'
export const UPDATE_LAYOUT = 'UPDATE_LAYOUT'

/*  SETTINGS  */
export const INIT_SETTINGS = 'INIT_SETTINGS'
export const RESET_SETTINGS = 'RESET_SETTINGS'
export const TOGGLE_SETTING = 'TOGGLE_SETTING'
export const UPDATE_SETTING = 'UPDATE_SETTING'

/*  WORKSPACES  */
export const CREATE_WORKSPACE = 'CREATE_WORKSPACE'
export const DELETE_WORKSPACE = 'DELETE_WORKSPACE'
export const INIT_WORKSPACES = 'INIT_WORKSPACES'
export const RESET_WORKSPACES = 'CLEAR_WORKSPACES'
export const UPDATE_WORKSPACE = 'UPDATE_WORKSPACE'
